# Default values for gitlab-kas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

annotations: {}
enabled: false
global: {}
hpa:
  targetAverageValue: 100m
image:
  repository: registry.gitlab.com/gitlab-org/cluster-integration/gitlab-agent/kas
  tag: latest-race
ingress:
  annotations: {}
  tls: {}
maxReplicas: 10
maxUnavailable: 1
minReplicas: 2
service:
  externalPort: 5005
  internalPort: 5005
  type: ClusterIP
serviceAccount:
  annotations: {}
