{{- if .Values.global.kas.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "gitlab.serviceAccount.name" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 -}}
  {{- with default .Values.serviceAccount.annotations .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
