{{- if .Values.networkPolicy.enabled | and .Values.global.minio.enabled }}
kind: NetworkPolicy
apiVersion: {{ template "minio.networkPolicy.apiVersion" . }}
metadata:
  name: {{ template "minio.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
{{ include "gitlab.immutableLabels" . | indent 6 }}
  ingress:
    - ports:
        - port: {{ .Values.servicePort }}
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels:
              {{ template "minio.fullname" . }}-client: "true"
      {{- end }}
{{- end }}
